FROM golang:1.10

RUN go get github.com/golang/dep/cmd/dep

WORKDIR /go/src/github.com/windmilleng/buildbench
ADD . .

# Download deps
RUN dep ensure

# Install
RUN go install github.com/windmilleng/buildbench/cmd/example

ENTRYPOINT /go/bin/example
